<?php
/**
 * Created by PhpStorm.
 * User: rohs
 * Date: 22.02.19
 * Time: 13:05
 */

namespace Omega\Policies;


use Illuminate\Support\Facades\Gate;

class OmegaGate extends Gate
{

    public static function define() {

        // if the authentified user is a super_admin we give him full access on the website
        parent::before(function ($user, $ability) {
            if ($user->hasRight('super_admin')) {
                return true;
            }
        });

        // then we define the gate
        parent::define('omega', 'Omega\Policies\OmegaPolicy@define');

    }

    public static function allows($ability)
    {
        return parent::allows('omega', $ability); // TODO: Change the autogenerated stub
    }

    public static function denies($ability)
    {
        return parent::denies('omega', $ability); // TODO: Change the autogenerated stub
    }

    public static function redirectBack(){
        toast()->warning(__('Access denied.'));
        return redirect()->route('admin.dashboard');
    }

    public static function accessDeniedView(){
        return view('policy.accessdenied');
    }
}